= Anypoint コネクタ開発
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: devkit, コネクタ, 開発, api, 認証, プロジェクト

このドキュメントでは、Anypoint コネクタ開発プロジェクトを開始し、コネクタを機能させ、必要な機能で強化するための決定事項と実行手順について簡単に説明します。これをコネクタ開発作業のロードマップとして使用できます。

== 前提条件

このドキュメントは、xref:index.adoc[Anypoint コネクタ DevKit] に精通し、xref:setting-up-your-dev-environment.adoc[「開発環境のセットアップ」]で指定されている適切なバージョンの DevKit、JDK、Anypoint DevKit プラグイン、Maven をインストールしていることを前提としています。

== コネクタ開発プロセスの概要

DevKit を使用してコネクタを開発する場合、ユースケースに従って、認証、接続、および対象での操作をコールして外部アプリケーションまたは他のリソースにデータを渡す方法に関する一連の決定が行われます。そして、これらの選択によって何を開発するかが決まります。このドキュメントでは、選択が必要なところで決定を下すのに役立つ情報、および詳細情報にアクセスするリンクが提供されます。



== ステップ 1 - API アクセスのセットアップ

. コネクタ用のテスト環境を準備します。詳細は対象システムによって大きく異なります。
. *SaaS* – 一部の SaaS アプリケーションでは、Sandbox は本番アカウントとは別のアカウントになる場合や、別のエンドポイントで回答する場合があります。
. *オンプレミス* – 一部のオンプレミスシステムまたは Web サービスでは、本番データではなくダミーデータを使用する個別のスタンドアロンインストールのみの場合があります。
. API ドキュメントなど、対象システムの既存のドキュメントをすべて入手します。

詳細な手順は、xref:setting-up-api-access.adoc[「API アクセスのセットアップ」]を参照してください。

== ステップ 2 - Anypoint コネクタプロジェクトの作成

. xref:creating-a-java-sdk-based-connector.adoc[「Java SDK ベースのコネクタの作成」]の手順に従って、開発環境でコネクタ開発プロジェクトを開始します。
. 対象システム用に提供されているクライアントライブラリやクラスライブラリなど、対象システムで必要な Java ライブラリを追加します。

完了したら、コネクタ用の最も基本的な機能を備えた Java クラスを含むスキャフォールディングプロジェクトの準備が整います。

== ステップ 3 - 認証

API で認証が必要な場合は、API が使用する認証方法を理解し、コネクタがサポートしている認証方法を選択します。ユースケースに基づき、下の表から認証方法を選択します。詳細は、サポートされるすべての方法が紹介されているxref:authentication.adoc[「認証」]を参照してください。

[%header,cols="2*"]
|===
|Authentication メソッド |注意事項
|xref:connection-management.adoc[接続管理] |SAML、Kerberos、LDAP、NTLM などの OAuth 以外のプロトコル、またはカスタム接続の作成に使用される最も簡単な認証モード。
|xref:oauth-v1.adoc[OAuth V1] |RESTful Web サービスとクラウドアプリケーションでよく使用されます。
|xref:oauth-v2.adoc[OAuth V2] |RESTful Web サービスとクラウドアプリケーションでよく使用されます。
|===

== ステップ 4 - 属性、操作、およびデータモデルの定義

コネクタ用に記述する Java コードの大部分は、コネクタの操作内で API をコールする方法と、それらの操作と Mule 間でコネクタがデータを渡す方法に関連しています。これは、API に基づいてコネクタ間で最も異なる領域です。

下の表を使用して、API のスタイルに基づいてコネクタを作成するためのアプローチを選択します。

[%header%autowidth.spread]
|===
|API の例 |注意事項
|xref:creating-a-connector-using-a-java-sdk.adoc[Java クライアントライブラリ] |公式または有名なサードパーティのライブラリが使用可能な場合、これは一般的に実装するのが最も簡単なコネクタスタイルであり、推奨されています。ほとんどのクライアントライブラリは、実際には SOAP または RESTful API のラッパーです。
|xref:creating-a-connector-for-a-soap-service-via-cxf-client.adoc[SOAP API] |SOAP Web サービスを作成およびコンシュームするための事実上の標準ライブラリであるこのスタイルは、クライアントロジックと XML への Java オブジェクトマッピングを処理します。Anypoint Studio では、指定した WSDL によってコネクタが自動的に作成されます。
|===



詳細は、xref:connector-attributes-and-operations.adoc[「コネクタの属性と操作」]を参照してください。

== ステップ 5 - 単体テストと機能テストの作成

本番対応コネクタには、一連の単体テストと機能テストが必要です。コネクタは標準の JUnit フレームワークを使用します。実際には、コネクタの操作を実装するときに単体テストを作成します。大きな成功を収めているコネクタの実装は、テスト駆動開発アプローチを使用しています。

. コネクタを使用する Mule フローを 1 つ以上開発します。
. テストを実行する xref:3.7@mule-runtime::functional-testing.adoc[FunctionalTestCase] のインスタンスを作成します。DevKit テストの場合、JUnit テストケース内で Mule を実行します。テストケースを作成するたびに、クラス xref:3.7@mule-runtime::functional-testing.adoc[FunctionalTestCase] (JUnit のサブクラス) を拡張します。テストケースは Mule Runtime インスタンスのライフサイクルを管理し、フローをコールしてテストを実行します。
. プログラムで各テストケースの結果を調べ、成功または失敗を判断します。

コネクタを世界中にリリースする前に、すべての操作を対象とした完全なテストスイートを実行し、主要な各コードパスを実行します。Maven が生成したプロジェクトには、開始時に役立つ 1 つのサンプルテストケースが `src/test/java` ディレクトリ内に含まれています。

JUnit を使用してコネクタテストケースを実装する方法についての詳細は、xref:developing-devkit-connector-tests.adoc[「DevKit コネクタテストの開発」]を参照してください。

== ステップ 6 - コネクタのドキュメント化

全機能を備えたコネクタにはドキュメントが必要です。DevKit では、コードサンプルを含む完全なリファレンスドキュメントを作成できます。

* コネクタに操作を追加するたびに、DevKit はソースコードのコメントにサンプル XML コードスニペットを追加する。これらのスニペットは、自動生成されたコネクタドキュメントに含まれます。
* 自動生成されたドキュメントを確認し、それを拡張して個々の操作の単純なドキュメントよりも多くの情報を提供するかどうかを決定する。

詳細は、xref:connector-reference-documentation.adoc[「コネクタリファレンスドキュメント」]を参照してください。

== ステップ 7 - コネクタのパッケージ化とリリース

コネクタを幅広い利用者にリリースされる準備が整ったら、次の追加手順を実行してユーザが確実に成功するようにします。

. コネクタをリリースする前に、ライセンス契約が締結済みであることを確認します。
. コネクタが内部使用のみを目的としている場合は、Eclipse 更新サイトとして共有できます。
. コネクタをコミュニティで共有するには、&#8203;https://www.anypoint.mulesoft.com/exchange/?type=connector&search=community[Anypoint Exchange] を参照してください。

詳細は、xref:packaging-your-connector-for-release.adoc[「リリースするコネクタのパッケージ化」]を参照してください。

== 関連情報

* xref:setting-up-your-dev-environment.adoc[「開発環境のセットアップ」]の理解。
