= MuleSoft コネクタ認定プログラムガイドライン
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: コネクタ, 認定, devkit, プログラムガイドライン

以下のセクションでは、コネクタ認定に必要な具体的な詳細について説明します。このプロセスの完全な概要については、&#8203;https://www.mulesoft.com/platform/cloud-connectors/certified[このページ]を参照してください。

== MuleSoft コネクタ認定プログラムとは?

MuleSoft のコネクタ認定プログラムでは、MuleSoft の認定を受けられる状態のエンタープライズグレードコネクタを作成するステップを順を追って説明します。認定されると、顧客や開発者は Anypoint Exchange でそのコネクタを見つけて使用できるようになります。

== 開始する前に

認定プログラムを開始する前に、次の点に留意して、以下の要件に準拠できることを確認してください。

* コネクタは、最新の状態と安全性が確保されていて、少なくとも 1 年に 1 回は再認定を受ける必要があります。
* コネクタは、Enterprise バージョンの MuleSoft ソフトウェアまたは MuleSoft サービスとして構築および配布される必要があります。
* コネクタのすべてのトランザクションは、MuleSoft を介することなく、顧客とパートナー間で発生します。
* コネクタは、フル機能で本番対応のエンタープライズグレードアプリケーション/プロトコルコネクタ (外部システムを使用して Mule に接続するコネクタ) である必要があります。
* コードは、継続的インテグレーション環境にデプロイできる状態になっている必要があります。コードは、非公開リポジトリをインポートすることなくコマンドラインからコンパイルできる必要があります。ログイン情報は個別に提供され、コンパイル時に設定できる必要があります。また、認定にはコネクタの Sandbox ログイン情報が必要になります。
* コネクタは、オープンソースまたは自分で所有するサードパーティライブラリのみを使用する必要があります。配布できないサードパーティライブラリは許可されません。
* 類似するコネクタがすでに https://www.mulesoft.com/exchange[Anypoint Exchange] に存在する場合でも、既存のコネクタよりも優れた追加機能を提供することが認められたコネクタは送信できます。

== サポートの提供

パートナーまたは開発者は、Anypoint Exchange のコネクタの​*完全なサポート*​を提供する必要があります。MuleSoft が受けるサポートの問い合わせについて、MuleSoft は商業的に合理的なレベルの一次電話電話対応や Web ベース/メールサポートを直接顧客に提供します。MuleSoft は、商業的な MuleSoft 製品にリンクする問題を引き受けて解決します。パートナーコネクタに固有の問題は、パートナーにエスカレーションされます。

* パートナーは、MuleSoft からエスカレーションされたすべてのサポートの問い合わせに *1 営業日*​以内に返答します。
* パートナーは、​*5 営業日*​以内にテクニカルサポートの問題解決に最善を尽くします。

== コネクタの価格設定

パートナーまたは開発者は、コネクタを無料で使用できるようにするのか、有料で使用できるようにするのかを独自の裁量で決定します。ただし、Anypoint Studio 内ではすべてのコネクタを無料で使用できるようにする必要があります。必須ではありませんが、コネクタのトライアル (デザインおよびデプロイメント用) を顧客に提供することをお勧めします。

[%header,cols="20,80"]
|===
a|
カテゴリ

 a|
詳細

| 無料 |顧客は、Anypoint Exchange でコネクタを無料でダウンロードして使用できます。
| 有料 |有料コネクタは、Anypoint Studio でデザイン時に Mule アプリケーションで使用できます。デプロイメントでは、コネクタはライセンスがないと実行されません。顧客は、パートナーから直接コネクタを購入し、xref:certified-connector-license-management.adoc[MuleSoft から提供される生成済みライセンスキー]を使用して、有料コネクタの使用を管理する必要があります。コネクタの価格は、パートナーが決定します。
|===

== ライセンス条件
LICENSE.md でライセンス条件の前に次の法的条件を追加してください。
****
*MuleSoft 認定コネクタについて*

MuleSoft 認定コネクタは、MuleSoft のパートナーおよび開発者コミュニティによって開発されています。これらのコネクタは、MuleSoft によってレビューおよび認定されています。 _[コネクタ名]_ コネクタを購入する場合や、そのサポートを受ける必要がある場合は、 _[パートナー名]_  (_[連絡先情報]_) に直接お問い合わせください。MuleSoft は、MuleSoft 認定コネクタのサポートの一切の義務を放棄します。

コネクタをインストールすると、お客様は、MuleSoft がお客様の連絡先情報をこのコネクタの開発者と共有して、お客様がコネクタに関する詳細情報を開発者から直接受信できるようにすることに同意したことになります。

*各自のライセンス条件*
****

== コンプライアンスのエクスポート
米国の法律で認められている場合を除き、MuleSoft から受け取った「MuleSoft の機密情報」や「MuleSoft ドキュメント」またはお客様の資料 (「パートナードキュメント」や「パートナーコネクタ」を含むがこれに限定されない) を使用することや、輸出または再輸出することはできません。特に、例外なく、「MuleSoft の機密情報」、「MuleSoft ドキュメント」およびお客様の資料は、次のいずれの者に対しても、輸出または再輸出を行うことができません。(a) 米国の通商禁止国 (b) 米国財務省の特別指定国リストまたは米国商務省の拒否人名リスト上の一切の者。お客様は、上記国家に住居を定めていないこと、あるいは上記リストに該当するものではないことを表明および保証するものとします。また、お客様は、お客様が米国の法律で禁止されている目的で「MuleSoft の機密情報」や「MuleSoft ドキュメント」およびお客様の資料を使用または再輸出しないことに同意していただいたものとし、当該目的には核、化学兵器もしくは生物兵器の開発、設計、製造または生産を含みますがこれらに限定されません。お客様が Anypoint Exchange でユーザに提供する資料が、関連する管轄の技術の輸出および輸入に関するすべての規制に準拠していることを保証する責任はすべてお客様が負うものとします。(「」で囲まれている用語は、認定コネクタパートナー契約と同じ定義を持つものとする)。

== 開発と認定

https://www.mulesoft.com/platform/cloud-connectors/certified#certification[このフォーム]に入力して、開発して認定を受けるコネクタをお知らせください。詳細については今後ご連絡いたします。
